"""empty message

Revision ID: d0a235e5b299
Revises: None
Create Date: 2015-12-28 10:50:50.442483

"""

# revision identifiers, used by Alembic.
revision = 'd0a235e5b299'
down_revision = None

from alembic import op
import sqlalchemy as sa

from datetime import datetime
from app import app

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    role_table = op.create_table(
        'role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    user_table = op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.Column('last_login_at', sa.DateTime(), nullable=True),
        sa.Column('current_login_at', sa.DateTime(), nullable=True),
        sa.Column('last_login_ip', sa.String(length=255), nullable=True),
        sa.Column('current_login_ip', sa.String(length=255), nullable=True),
        sa.Column('login_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    op.create_table(
        'connection',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('provider_id', sa.String(length=255), nullable=True),
        sa.Column('provider_user_id', sa.String(length=255), nullable=True),
        sa.Column('access_token', sa.String(length=255), nullable=True),
        sa.Column('secret', sa.String(length=255), nullable=True),
        sa.Column('display_name', sa.String(length=255), nullable=True),
        sa.Column('profile_url', sa.String(length=512), nullable=True),
        sa.Column('image_url', sa.String(length=512), nullable=True),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ru_table = op.create_table(
        'roles_users',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
        )
    ### end Alembic commands ###

    op.bulk_insert(
        user_table,
        [
            {
                'email': app.config['ADMIN_EMAIL'],
                'password': app.config['ADMIN_PASSWD'],
                'active': True,
                'confirmed_at': datetime.utcnow()
            }
        ]
    )

    op.bulk_insert(
        role_table,
        [
            {
                'name': 'Admin',
                'description': 'Manage the application'
            },
            {
                'name': 'User',
                'description': 'Use the application'
            },
        ]
    )

    op.bulk_insert(
        ru_table,
        [
            {
                'user_id': 1,
                'role_id': 1
            },
            {
                'user_id': 1,
                'role_id': 2
            },
        ]
    )




def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('connection')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
